version: '2'

services:
    web:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - ./code:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php:
        image: php:fpm
        build:
            context: _php
            dockerfile: Dockerfile
        volumes:
            - ./code:/code
        networks:
            - code-network
    redis:
        image: "redis:alpine"
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
