apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: php
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: php
    spec:
      containers:
      - image: php:fpm
        name: php
        resources: {}
        volumeMounts:
        - mountPath: /code
          name: php-claim0
      restartPolicy: Always
      volumes:
      - name: php-claim0
        persistentVolumeClaim:
          claimName: php-claim0
status: {}
