apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        resources: {}
      restartPolicy: Always
status: {}
