apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - image: nginx:latest
        name: web
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /code
          name: web-claim0
        - mountPath: /etc/nginx/conf.d/default.conf
          name: web-claim1
      restartPolicy: Always
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
      - name: web-claim1
        persistentVolumeClaim:
          claimName: web-claim1
status: {}
